### ISSUE TITLE
pathweaver auto path intergration

### ISSUE THREAD

**Issue by roterrex** [EMU4729/FRC2023#2]

**Comment by neelkarma** [comment]
https://github.com/EMU4729/FRC2023/commit/db28317b2f3eb475c5c4dd78eaf29c32f1a63485 :smile: :smile: :smile: :smile: :smile: :smile: :smile: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by neelkarma** [comment]
close?

**Comment by neelkarma** [comment]
simulation is working !!! :D:D:D
