### ISSUE TITLE
servo bounds for -1 to 1 range

### ISSUE THREAD

**Issue by modelmat** [EMU4729/FRC2023#8]
![image](https://user-images.githubusercontent.com/25718989/212588276-5538c273-5bf1-49ff-b98d-1a2976e46f44.png)

from the user guide: https://cdn.andymark.com/media/W1siZiIsIjIwMTkvMDMvMjIvMTAvMjYvNDMvZjQzZTk3NzMtN2MxNi00MDIwLWE5YTgtMTA4MDliMTMxZDExL1VzaW5nIEwxNiBMaW5lYXIgU2Vydm8gMDMtMjAxOS5wZGYiXV0/Using%20L16%20Linear%20Servo%2003-2019.pdf?sha=7b43b981c4f1c13d

**Comment by neelkarma** [comment]
done in https://github.com/EMU4729/FRC2023/commit/0ca166e868c97aeb1eb9fe9fc29bc5b2ccbebaa0
